export const experiences = [
  {
    year: "2025",
    company: "Bigglz",
    position: "Web Frontend Developer",
    tech: "React, TypeScript, Next.js",
    description: "'Bigglz' Web Frontend Developer",
    capability: 100, // 역량 점수 (0-100)
    category: "PROGRAMMING",
  },
  {
    year: "2024",
    company: "9oormthonUNIV",
    position: "Full Stack Developer",
    tech: "React, TypeScript, Nest.js",
    description: "'9oormthonUNIV' Web Development Team",
    capability: 80,
    category: "PROGRAMMING",
  },
  {
    year: "2024",
    company: "Blockchain at Yonsei",
    position: "Dapp Developer",
    tech: "Solidity, Web3.js, React",
    description: "'Blockchain at Yonsei' Dapp Developer Team",
    capability: 85,
    category: "PROGRAMMING",
  },
  {
    year: "2024",
    company: "Cosmostation",
    position: "Frontend Developer Intern",
    tech: "React, TypeScript, Svelte, D3.js, Chart.js",
    description: "'Cosmostation' Web Frontend Developer Intern",
    capability: 95,
    category: "PROGRAMMING",
  },
  {
    year: "2022",
    company: "Memory Plant",
    position: "Social Media Intern",
    tech: "Adobe Suite, Figma, Canva",
    description: "'Memory Plant' Social Media Intern",
    capability: 65,
    category: "SAAS SYSTEMS",
  },
  {
    year: "2022",
    company: "PTPI",
    position: "Club Leader",
    tech: "Project Management, Team Leadership",
    description: "Leader of Volunteering club 'PTPI'",
    capability: 80,
    category: "DATABASE STRUCTURE",
  },
];
